SECTION TEXT
INPUT N ;N=1
LOAD ONE ;ACC=1
STORE CURR ;CURR =1
STORE LAST ;LAST =1
LOAD N ;ACC=1
JMPZ END ;NOPE
SUB ONE ;ACC=0
JMPZ END ;NOPE
STORE N; N=2
L1: LOAD CURR ;ACC=3
    ADD LAST ;ACC=5
    STORE AUX ;AUX=5
    LOAD CURR ;ACC=3
    STORE LAST ;LAST=3
    LOAD AUX ;ACC=5
    STORE CURR ;CURR=5
    LOAD N ;ACC=1
    SUB ONE ;ACC=0
    STORE N ;N=0
    JMPZ END
    JMP L1
END: OUTPUT CURR ;OUT=5
STOP
SECTION DATA
LAST: SPACE
CURR: SPACE
AUX: SPACE
ONE: CONST 1
N: SPACE
